server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://172.23.27.118:3306/netdisk?
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  mail:
    host: smtp.qq.com
    username: 1789023580@qq.com
    password: reoaiaspqjfbeddg
    from: 1789023580@qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  mvc:
    date-format: yyyy-MM-dd

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB

ceph:
  endpoint: http://172.23.27.119:7480
  ak: U6DVKQNYCPHCIIP0XZFJ
  sk: A32aqcbXEECBtfxL2UqqBoMs2zyJJBMnRpG0gj7i

mybatis:
  type-aliases-package: com.cooper.demo.Mapper
  mapper-locations: classpath:mybatis/mapper/*.xml

mybatis-plus:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:/mybatis/mapper/*.xml
  # 注意：对应实体类的路径//entity扫描的包名
  type-aliases-package: com.cooper.demo.Bean
  #  type-handlers-package: com.unnet.netdisk.config.typeHandle # 自定义TypeHandler所在包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
    call-setters-on-nulls: true
  global-config:
    banner: false


logging:
  level:
    com.cooper.demo.Mapper: debug

